### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by dhruv-m1**
**Summary of changes**

* fix issue with package.json & node_modules
* connect backend with frontend
* connect backend to new mongodb instance
* fullstack authentication
* popout modals removed in UI (to be shfited to individual pages)
* header styling broken (to be rectified with search feature)
* restructured to be more manageble (researched)

Kindly Review

### CODE REVIEW

**Review by corbynkwan — APPROVED** [review]
LGBM!

**Review by amy34268 — APPROVED** [review]
Looks good!

**Review by ZehaoLu98 — COMMENTED** [review]
Nice!

**Review by ZehaoLu98 — APPROVED** [review]

**Comment by dhruv-m1** [comment]
merged

**Pull request merged**
